apiVersion: v1
entries:
  tehik-template:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-02-01T19:12:17.717966+02:00"
    dependencies:
    - name: common
      repository: file://../common
      version: 0.5.1
    - condition: rabbitmq.enabled
      name: rabbitmq
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 12.7.0
    - condition: postgresql.enabled
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 13.2.30
    description: Tehik KTI template chart
    digest: 1b50742b08c52949c743aef35ff1be898aefd0b8e427523c10836edb65c71b02
    maintainers:
    - email: tarmo@rebahn.eu
      name: Tarmo Katmuk
    name: tehik-template
    type: application
    urls:
    - https://rebahn-devops.github.com/tehik-template/charts/tehik-template-0.1.1.tgz
    version: 0.1.1
generated: "2024-02-01T19:12:17.710311+02:00"
